### ISSUE TITLE
NEW conditional admin icon

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-elemental-testimonials#21]
```yml
---
Only:
  moduleexists: 'ryanpotter/silverstripe-cms-theme'
---
Dynamic\Elements\Admin\TestimonialsAdmin:
  menu_icon_class: 'far fa-comment-alt'
```
